### PR TITLE
Added support for Flutter Icon on Pad Button View

### PR DESCRIPTION
**Pull request by ferrets6**
Added support for Flutter Icon on Pad Button View.
I needed to use like in the pic.

Untitled

P.S.: thank you for this awsome control pad! :D

### CODE REVIEW

**Comment by artur-ios-dev** [comment]
Thanks for the PR. I will review it soon.

**Comment by artur-ios-dev** [comment]
@ferrets6 Any reason to use relative import here?

**Comment by ferrets6** [comment]
No, sorry!
I'm quite new on Flutter and github.

These two commits were intendend only for my local use, I had problems on build without them.
They weren't supposed to be added on the pull request.

image

**Comment by artur-ios-dev** [comment]
@ferrets6 You can simply checkout your branch (or you probably have it already?) and just revert those import changes. Thanks!

**Comment by ferrets6** [comment]
@artrmz done!

**Review by artur-ios-dev — APPROVED** [review]
LGTM 💯Thank you!

**Pull request merged**
